### ISSUE TITLE
Dev Task: Django Initial Setup

### ISSUE THREAD

**Issue by Vishalchapa** [Vishalchapa/MIMO#20]
As a **developer**, I want to **setup django project**, for an **initial development**
**Acceptance Criteria**
* Install Django
* Create Mimo Project
* Database Setup with PostgreSQL
* Heroku Deployment
* Sensitive Data inside the env file to be hidden
**Task**
- [ ] Install Django
- [ ] Create Mimo Project
- [ ] Database Setup with PostgreSQL
- [ ] Setup whitenoise to handle static files
- [ ] Create Apps
- [ ] Create Template
- [ ] Initial Deployment on heroku for test
